name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-gate:
    name: Build Gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build all derivations
        run: >-
          nix build --quiet
          .#default
          .#devShells.x86_64-linux.default.inputDerivation

  build:
    needs: build-gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build --quiet

  formatting:
    name: Check code formatting
    needs: build-gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check formatting
        run: nix develop --quiet -c just format-check
